org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# Emulador local: http://10.0.2.2:4000
# Celular na Wi-Fi: http://SEU_IP_LAN:4000
# Produção (Render + MongoDB Atlas):
API_BASE_URL=https://jp-moda-minimalista.onrender.com

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
